# This workflow will install Python dependencies and run the script

name: Run script

on:
  workflow_dispatch: # add run button in github
  schedule:
    - cron: "15 12 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env:
        HDX_SITE: ${{ vars.HDX_SITE }}
        HDX_KEY: ${{ secrets.HDX_BOT_SCRAPERS_API_TOKEN }}
        PREPREFIX: ${{ secrets.PREPREFIX }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
      run: |
        python run.py
#    - name: Commit updated data bundle
#      if: success()
#      uses: stefanzweifel/git-auto-commit-action@v4
#      with:
#        file_pattern: "metric_dates.txt"
#        commit_message: automatic - Data bundle updated
#        push_options: "--force"
#        skip_dirty_check: false
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{secrets.HDX_PIPELINE_EMAIL_SERVER}}
        server_port: ${{secrets.HDX_PIPELINE_EMAIL_PORT}}
        username: ${{secrets.HDX_PIPELINE_EMAIL_USERNAME}}
        password: ${{secrets.HDX_PIPELINE_EMAIL_PASSWORD}}
        subject: "FAILED: ${{github.repository}} run job"
        body: GitHub Actions run job for ${{github.repository}} failed!
        to: ${{vars.HDX_PIPELINE_EMAIL_LIST}}
        from: ${{secrets.HDX_PIPELINE_EMAIL_FROM}}
        content_type: text/html
